# Deployment of nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepops-website
  labels:
    app: deepops-website
    app.kubernetes.io/name: deepops-website
spec:
  selector:
    matchLabels:
      app: deepops-website
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: deepops-website
        app.kubernetes.io/name: deepops-website
    spec:
      imagePullSecrets:
        - name: ghcrio-registry
      containers:
        - name: deepops-website
          image: ghcr.io/deepshore/deepops-website:pr-4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: deepops-website-config
