name: cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ## Sets environment variable
  BACKEND_URL: https://deepshore.de

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: contains(github.ref, 'refs/heads/main')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: deepops.de

